"""news table

Revision ID: 92e79ab207b2
Revises: 092aa357e7ff
Create Date: 2019-12-10 16:02:53.462427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e79ab207b2'
down_revision = '092aa357e7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=140), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('author', sa.String(length=140), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_news_timestamp'), 'news', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_timestamp'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
